### PR TITLE
topic modeling cluster script

### PR DESCRIPTION
**Pull request by paxtonfitzpatrick**
to run, will need to:
- move `cluster-scripts` directory to `/dartfs/rc/lab/D/DBIC/CDL/f0028ph/MIND-narrative-modeling/cluster-scripts`
- add @jeroenvanbaar's `helpers.py` to `/dartfs/rc/lab/D/DBIC/CDL/f0028ph/MIND-narrative-modeling/cluster-scripts`
- set number of nodes, processors per node, and wall time
- make sure conda environment has all necessary modules installed

### CODE REVIEW

**Comment by jeremymanning** [comment]
@paxtonfitzpatrick looks like there's a merge conflict 😿.  Also, do you want me to actually review this in detail or just merge once the conflict is resolved?

**Comment by paxtonfitzpatrick** [comment]
@jeremymanning the conflict is just that there were two copies of my `get_events.ipynb` notebook and I deleted the older one... not sure why it doesn't like that 😕 

And can you please do a quick check over the config, submit, and cruncher files?  That's really all I need

**Comment by paxtonfitzpatrick** [comment]
Oh, I also updated the remote tracking branch of the cluster tools submodule, and I think I did it in a way that when other people pull it will update for them, but I'm not certain.  

might have to do `git submodule update`

**Comment by paxtonfitzpatrick** [comment]
@jeremymanning fixed 🎉

**Review by jeremymanning — APPROVED** [review]
this pull request looks good-- but there are some issues with the submodule (cluster-tools-dartmouth), which is (it seems like) what you're asking me to look at.  but i think you need to submit a separate pull request to get those changes into a format that i can review.  or we can just go over them in person during the hackathon time.

**Comment by paxtonfitzpatrick** [comment]
either works for me! I just created this https://github.com/ContextLab/cluster-tools-dartmouth/pull/6 so you can compare and comment if that's easier for you

**Pull request merged**
