### PR TITLE
fixed bug in making cooccurence matrices

### PR DESCRIPTION
**Pull request by vassiki**
I was taking combinations of the list of characters in each event when I should have been taking permutations to get all symmetric pairs. In this commit, I also added a toy dataset with a test to check if the matrix is symmetric because clearly, my eyes don't work 😨 Here is the updated gif for your 👀 though! 
cooccurence

Pop quiz: Why do the first two characters never recurr? A chocolate for anyone who can guess!!

### CODE REVIEW

**Comment by paxtonfitzpatrick** [comment]
@vassiki this is so cool!!

**Comment by jeremymanning** [comment]
neat!

**Comment by jeremymanning** [comment]
are the characters ordered by first appearance?

**Comment by vassiki** [comment]
sorry, just seeing this. Yep, they are! Unique character names get added to a list the first time they appear!

**Pull request merged**
